default_platform(:android)

# Add this at the top of your Fastfile to load the JSON file
secrets = JSON.parse(File.read('../secret.json'))

platform :android do

  desc "Deploy to Firebase"
  lane :deploy_firebase do 
    firebase_app_distribution(
      groups: "testers",
      release_notes: "Bug fixed and improvements.",
      apk_path: "../build/app/outputs/flutter-apk/app-release.apk",
      firebase_cli_path: "/usr/local/bin/firebase",
      firebase_cli_token: secrets["firebase_cli_token"],
      app: secrets["app_id"]
    )
  end

  desc "Get-Set Version Android"
  lane :set_version do |options|
    version_name = options[:version_name] || android_get_version_name(gradle_file: "app/build.gradle")
    version_code = options[:version_code] || android_get_version_code(gradle_file: "app/build.gradle")
  
    android_set_version_name(
      version_name: version_name,
      gradle_file: "app/build.gradle" 
    )
  
    android_set_version_code(
      version_code: version_code,
      gradle_file: "app/build.gradle" 
    )
  end

  desc "Deploy a new version to the Firebase App Distribution"
  lane :deploy do |options|
    options[:version_name] ||= nil  # Make version_name optional
    options[:version_code] ||= nil  # Make version_code optional
    set_version(options)
    deploy_firebase()
  end
end
