# Name of the GitHub Actions workflow
name: CI

# Trigger the workflow on pull requests to the master branch
on:
  pull_request:
    branches:
      - master

  # Allow manual triggering of the workflow with release_notes input
  workflow_dispatch:
    inputs:
      release_notes:
        type: string
        required: true
        default: "Manuel Debug Build"

# Define the jobs to be executed in the workflow
jobs:
  # Job to run Flutter tests and analysis
  flutter_test:
    # Name of the job
    name: Run flutter test and analyze
    
    # Operating system for the job
    runs-on: ubuntu-latest
    
    # Steps to be executed in the job
    steps:
      # Checkout the source code of the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Flutter using the subosito/flutter-action action
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      # Get dependencies using Flutter pub get
      - name: Get dependencies
        run: flutter pub get

      # Analyze the Flutter project
      - name: Analyze project
        run: flutter analyze

      # Run Flutter tests
      - name: Run tests
        run: flutter test
